/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import domain.TZadatak;
import controller.Controller;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import ui.component.table.model.ZadatakTableModel;

/**
 *
 * @author Bron Zilar
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        fillForm();
        imenujKolone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblZadaci = new javax.swing.JTable();
        jbtnDodajNoviZadatak = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna ekranska forma");

        jtblZadaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblZadaci);

        jbtnDodajNoviZadatak.setText("Dodaj novi zadatak");
        jbtnDodajNoviZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajNoviZadatakActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDodajNoviZadatak)
                    .addComponent(jbtnSacuvaj))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDodajNoviZadatak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajNoviZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajNoviZadatakActionPerformed
        JDialog form = new FNoviZadatak(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_jbtnDodajNoviZadatakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajNoviZadatak;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTable jtblZadaci;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        List<TZadatak> zadaci = Controller.getInstance().getAllZadaci();
        TableModel tm = new ZadatakTableModel(zadaci);
        jtblZadaci.setModel(tm);
        
    }

    private void imenujKolone() {
        jtblZadaci.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Sifra zadatka");
        jtblZadaci.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Naziv");
        jtblZadaci.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Opis");
        jtblZadaci.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Datum");
        jtblZadaci.getTableHeader().getColumnModel().getColumn(4).setHeaderValue("Ime radnika");
        jtblZadaci.getTableHeader().getColumnModel().getColumn(5).setHeaderValue("Prezime radnika");
    }

    public JTable getJtblZadaci() {
        return jtblZadaci;
    }
       
    public void dodavanjZadataka() {
        TableModel tm = jtblZadaci.getModel();
        ZadatakTableModel ztm = (ZadatakTableModel) tm;
        for(TZadatak zadatak : Controller.getInstance().getAllZadaci()) {
                    ztm.addZadatak(Controller.getInstance().getAllZadaci().get(0));
        }
    }
}
