package ui.form;

import controller.Kontroler;
import domain.Lokacija;
import domain.Radnik;
import domain.Raspored;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import table.model.RasporedTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bron Zilar
 */
public class FUnosRasporeda extends javax.swing.JFrame {
    
    /**
     * Creates new form FUnosRasporeda
     */
    public FUnosRasporeda() {
        initComponents();
        setLocationRelativeTo(null);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbLokacija = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcmbRadnik = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtxtBrojSati = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxdDatum = new javax.swing.JTextField();
        jbtnDodajRaspored = new javax.swing.JButton();
        jbtnObrisiRaspored = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRaspored = new javax.swing.JTable();
        jbtnSacuvajRasporede = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[FON] Unos rasporeda");

        jLabel1.setText("Lokacija:");

        jLabel2.setText("Radnik:");

        jLabel3.setText("Broj sati:");

        jLabel4.setText("Datum (dd.MM.yyyy):");

        jbtnDodajRaspored.setText("Dodaj raspored");
        jbtnDodajRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajRasporedActionPerformed(evt);
            }
        });

        jbtnObrisiRaspored.setText("Obrisi raspored");
        jbtnObrisiRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiRasporedActionPerformed(evt);
            }
        });

        jtblRaspored.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblRaspored);

        jbtnSacuvajRasporede.setText("Sacuvaj rasporede");
        jbtnSacuvajRasporede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajRasporedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbtnDodajRaspored))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnObrisiRaspored)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcmbLokacija, 0, 305, Short.MAX_VALUE)
                                .addComponent(jcmbRadnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtBrojSati)
                                .addComponent(jtxdDatum))))
                    .addComponent(jbtnSacuvajRasporede, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxdDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajRaspored)
                    .addComponent(jbtnObrisiRaspored))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSacuvajRasporede)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajRasporedActionPerformed
        Lokacija lokacija = (Lokacija) jcmbLokacija.getSelectedItem();
        Radnik radnik = (Radnik) jcmbRadnik.getSelectedItem();
        String br = jtxtBrojSati.getText().trim();
        String dat = jtxdDatum.getText().trim();
        
        if(br.isEmpty() || dat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja");
            return;
        }
        int brojSati=0;
        try {
            brojSati = Integer.parseInt(br);
        } catch(NumberFormatException ex) {
            System.out.println("Broj sati mora biti ceo broj");
            return;
        }
                     
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = null;
        try {
            datum = sdf.parse(dat);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum mora biti u odgovarajucem formatu dd.MM.yyyy");
        }
        
        
        
        Raspored raspored = new Raspored(-1, brojSati, datum, lokacija, radnik);
        RasporedTableModel rtm = (RasporedTableModel) jtblRaspored.getModel();
        rtm.dodaj(raspored);
    }//GEN-LAST:event_jbtnDodajRasporedActionPerformed

    private void jbtnObrisiRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiRasporedActionPerformed
        int red = jtblRaspored.getSelectedRow();
        if(red == -1) {
            JOptionPane.showMessageDialog(this, "Morate prvo selektovati red");
        } else {
            RasporedTableModel rtm = (RasporedTableModel) jtblRaspored.getModel();
            rtm.obrisi(red);
        }
    }//GEN-LAST:event_jbtnObrisiRasporedActionPerformed

    private void jbtnSacuvajRasporedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajRasporedeActionPerformed
        RasporedTableModel rtm = (RasporedTableModel) jtblRaspored.getModel();
        List<Raspored> rasporedi = rtm.getRasporedi();
        
        for (int i = 0; i < rasporedi.size(); i++) {
            Raspored r1 = rasporedi.get(i);
            for (int j = i+1; j < rasporedi.size(); j++) {
                Raspored r2 = rasporedi.get(j);
                if(r1.getRadnik().getRadnikId()==r2.getRadnik().getRadnikId() && r1.getLokacija().getLokacijaID() != r2.getLokacija().getLokacijaID()) {
                    JOptionPane.showMessageDialog(this, "Ne moze jedan radnik biti rasporedjen na dve lokacije", "Greska", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }          
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        for (int i = 0; i < rasporedi.size(); i++) {
            Raspored r1 = rasporedi.get(i);
            int ukupnoSati = r1.getBrojSati();
            String dat1 = sdf.format(r1.getDatum());
            for(int j = i+1; j < rasporedi.size(); j++) {
                Raspored r2 = rasporedi.get(j);
                String dat2 = sdf.format(r2.getDatum());
                if(r1.getRadnik().getRadnikId()==r2.getRadnik().getRadnikId() && dat1.equals(dat2)) {
                     ukupnoSati+=r2.getBrojSati();
                }
                if(ukupnoSati>8) {
                     JOptionPane.showMessageDialog(this, "Radnik moze raditi 8 sati najvise istog dana", "Greska", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            boolean sacuvano = Kontroler.getInstanca().sacuvaj(rasporedi);
            // Iz nekog razloga dva puta sacuva, nzm zasto ???
            if(sacuvano) {
                JOptionPane.showMessageDialog(this, "Uspesno sacuvano");
            }
            else {
                JOptionPane.showMessageDialog(this, "Cuvanje nije uspelo");
            }
        }
    }//GEN-LAST:event_jbtnSacuvajRasporedeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajRaspored;
    private javax.swing.JButton jbtnObrisiRaspored;
    private javax.swing.JButton jbtnSacuvajRasporede;
    private javax.swing.JComboBox jcmbLokacija;
    private javax.swing.JComboBox jcmbRadnik;
    private javax.swing.JTable jtblRaspored;
    private javax.swing.JTextField jtxdDatum;
    private javax.swing.JTextField jtxtBrojSati;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        popuniLokacije();
        popuniRadnike();
        srediTabelu();
        
        
        
    }

    private void popuniLokacije() {
        List<Lokacija> lokacije = new ArrayList<>();
        try {
            lokacije = Kontroler.getInstanca().vratiSveLokacije();
            for (Lokacija lokacija : lokacije) {
                jcmbLokacija.addItem(lokacija);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUnosRasporeda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniRadnike() {
        List<Radnik> radnici = new ArrayList<>();
        try {
            radnici = Kontroler.getInstanca().vratiSveRadnike();
            for (Radnik radnik : radnici) {
                jcmbRadnik.addItem(radnik);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUnosRasporeda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediTabelu() {
        RasporedTableModel rtm = new RasporedTableModel();
        jtblRaspored.setModel(rtm);
    }
}
